ConstructionWaste/Controllers/AdminControllers/CarController.cs
using AutoMapper;
using ConstructionWaste.DTOs.Car;
using ConstructionWaste.Models;
using DAL.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Services.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;

namespace ConstructionWaste.Controllers.AdminControllers
{
    [Authorize(Roles = "admin")]
    public class CarController : Controller
    {
        public readonly IUOW _service;
        private readonly IMapper _mapper;

        public CarController(IUOW service, IMapper mapper)
        {
            _service = service;
            _mapper = mapper;
        }

        public IActionResult CarList()
        {
            var dbModel = _service.Car.GetAllCar();
            var cars = _mapper.Map<IEnumerable<CarDTO>>(dbModel);

            return View(cars.OrderByDescending(x=>x.Id).Take(10));
        }

        public IActionResult CarDrivers()
        {
            var dbModel = _service.CarDriver.GetAllCarDriver();
            var carDrivers = _mapper.Map<IEnumerable<CarDriverDTO>>(dbModel);

            return View(carDrivers.OrderByDescending(x=>x.Id).Take(10));
        }

        public IActionResult CarDriver(int id)
        {
            var dbModel = _service.CarDriver.GetCarDriverByCar(id);
            var car=_mapper.Map<CarDriverDTO>(dbModel);
            return View(car);
        }

        public IActionResult AddCarAndDriver()
        {
            CarVM model = new CarVM();
            return View(model);
        }

        [HttpPost]
        public IActionResult AddCarAndDriver(CarVM model)
        {
            model.Car.Id = _service.Car.AddId();
            model.CarDriver.Id = _service.CarDriver.AddId();
            model.Car.CreatedAt = model.CarDriver.CreatedAt = DateTime.Now;
            model.CarDriver.CarId = model.Car.Id;

            if (!ModelState.IsValid)
                return View(model);

            var newCar = _mapper.Map<Car>(model.Car);
            var newCarDriver = _mapper.Map<CarDriver>(model.CarDriver);

            _service.Car.Create(newCar);
            _service.CarDriver.Create(newCarDriver);
            _service.Commit();

            return RedirectToAction(nameof(CarList));
        }

        public IActionResult EditCarAndDriver(int id)
        {
            CarVM model = new CarVM();
            var editCar = _service.Car.GetCar(id);
            var editCarDriver = _service.CarDriver.GetCarDriverByCar(editCar.Id);

            model.Car = _mapper.Map<CarDTO>(editCar);
            model.CarDriver = _mapper.Map<CarDriverDTO>(editCarDriver);

            return View(model);
        }

        [HttpPost]
        public IActionResult EditCarAndDriver(CarVM model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var editCar = _service.Car.GetCar(model.Car.Id);
            var editCarDriver = _service.CarDriver.GetCarDriverByCar(model.Car.Id);
            if(editCar == null && editCarDriver == null)
            {
                throw new Exception("object not found");
                
            }

            Car x=_mapper.Map<CarDTO, Car>(model.Car, editCar);
            CarDriver y=_mapper.Map<CarDriverDTO, CarDriver>(model.CarDriver, editCarDriver);
            _service.Car.Update(x);
            _service.CarDriver.Update(y);
            _service.Commit();

            return RedirectToAction(nameof(CarList));
        }

        [HttpPost]
        public IActionResult DeleteCarAndDriver(int id)
        {
            var deleteCar = _service.Car.GetCar(id);
            var deleteCarDriver = _service.CarDriver.GetCarDriverByCar(deleteCar.Id);

            _service.Car.Delete(deleteCar);
            _service.CarDriver.Delete(deleteCarDriver);
            _service.Commit();

            return RedirectToAction(nameof(CarList));
        }



    }
}

ConstructionWaste/Controllers/AdminControllers/ClientController.cs
using AutoMapper;
using ConstructionWaste.DTOs.Clients;
using ConstructionWaste.Models;
using DAL.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Services.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;

namespace ConstructionWaste.Controllers.AdminControllers
{
    [Authorize(Roles = "admin")]
    public class ClientController : Controller
    {
        public readonly IUOW _service;
        private readonly IMapper _mapper;

        public ClientController(IUOW service, IMapper mapper)
        {
            _service = service;
            _mapper = mapper;
        }

        public IActionResult ClientList(string SearchTerm)
        {
            var Modenl = _service.Client.GetAllClient(SearchTerm);

            var ClientList = _mapper.Map<IEnumerable<ClientsDTO>>(Modenl);

            return View(ClientList.OrderByDescending(x=>x.Id).Take(10));
        }

        public IActionResult AddClient()
        {
            ClientVM newClient = new ClientVM();
            var clientsType = _service.Client.GetClientTypes();
            
            newClient.ClientTypeList = _mapper.Map<IEnumerable<ClientTypeDTO>>(clientsType);

            return View(newClient);
        }

        [HttpPost]
        public IActionResult AddClient(ClientVM newClient)
        {
            if (!ModelState.IsValid)
            {
                return View(newClient);
            }
            //newClient.Client.TypeId = newClient.ClientType.Id;
            newClient.Client.InsertTime = DateTime.Now;
            newClient.Client.TypeId = 3;

            Client dbModel=_mapper.Map<Client>(newClient.Client);

            dbModel.Id=_service.Client.getId();
            _service.Client.Create(dbModel);
            _service.Commit();

            return RedirectToAction(nameof(ClientList));
        }

        public IActionResult EditClient(int Id)
        {
            var client = _service.Client.GetClient(Id);
            var model = _mapper.Map<ClientTest>(client);
            return View(model);
        }

        [HttpPost]
        public IActionResult EditClient(ClientTest model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            model.TypeId = 4;
            var dbModel = _service.Client.GetClient(model.Id);

            if (dbModel == null)
            {
                throw new Exception("object not found");
            }

            _mapper.Map<ClientTest,Client>(model,dbModel);
            _service.Client.Update(dbModel);
            _service.Commit();

            return RedirectToAction(nameof(ClientList));
        }

        [HttpPost]
        public IActionResult DeleteClient(int id) 
        {
            var client = _service.Client.GetClient(id);
            _service.Client.Delete(client);
            _service.Commit();

            return RedirectToAction(nameof(ClientList));
        }


    }

}

ConstructionWaste/Controllers/AuthController.cs
using System.Threading.Tasks;
using ConstructionWaste.DTOs.Auth;
using DAL.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;


namespace ConstructionWaste.Controllers
{
    
    public class AuthController : Controller
    {
        private readonly UserManager<AppUser> userManager;
        private readonly SignInManager<AppUser> signInManager;

        public AuthController(UserManager<AppUser> userManager, SignInManager<AppUser> signInManager)
        {
            this.userManager = userManager;
            this.signInManager = signInManager;
        }

        public IActionResult Login()
        {
            
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginDTO details)
        {
            if (ModelState.IsValid)
            {
                AppUser user = await userManager.FindByEmailAsync(details.Email);
                if (user != null)
                {
                    await signInManager.SignOutAsync();
                    Microsoft.AspNetCore.Identity.SignInResult result =
                        await signInManager.PasswordSignInAsync(user, details.Password, false, false);
                    var IsAdmin = await userManager.IsInRoleAsync(user, "admin");
                    var IsUser= await userManager.IsInRoleAsync(user, "user");
                    

                    if (result.Succeeded)
                    {
                       // RedirectToAction("Index", "student");
                        
                        if (IsAdmin)
                           return RedirectToAction("Index", "Home");
                        else if (IsUser)
                           return RedirectToAction("Privacy", "Home");

                    }
                    ModelState.AddModelError("", "Invalid user or password");
                }
                
            }
            return View(details);
        }

        public async Task<IActionResult> Logout()
        {
            await signInManager.SignOutAsync();
            return RedirectToAction(nameof(Login));
        }


        [AllowAnonymous]
        public IActionResult AccessDenied()
        {
            return View();
        }
    }
}

ConstructionWaste/Controllers/RegistrationController.cs
using System.Threading.Tasks;
using AutoMapper;
using ConstructionWaste.DTOs.Registration;
using DAL.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace ConstructionWaste.Controllers
{
    public class RegistrationController : Controller
    {
        private readonly UserManager<AppUser> userManager;
        private readonly IMapper _mapper;

        public RegistrationController(UserManager<AppUser> userManager, IMapper mapper)
        {
            this.userManager = userManager;
            _mapper = mapper;
           
        }
        public IActionResult UserRegistration()
        {
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> UserRegistration(RegistrerUserDTO model)
        {

            
            if (ModelState.IsValid)
            {
                var user = _mapper.Map<AppUser>(model);
                IdentityResult result = await userManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {
                    await userManager.AddToRoleAsync(user, "user");

                    return RedirectToAction("Login","Auth");
                }
                else
                {
                    AddErrorsFromResult(result);
                }
            }
            return View(model);
        }

        

        private void AddErrorsFromResult(IdentityResult result)
        {
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError("", error.Description);
            }
        }
    }
}

ConstructionWaste/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ConstructionWaste</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="nav-link text-dark" asp-area="" asp-controller="Client" asp-action="ClientList">clients</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="UserService" asp-action="Users">Users</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Car" asp-action="CarList">clients</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Client" asp-action="Join">Privacy</a>
                        </li>
                        @if (User?.Identity?.IsAuthenticated ?? false)
                        {

                            <li class="nav-item active">
                                Hello @User.Identity.Name
                                <a asp-controller="Auth" asp-action="Logout">გასვლა</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item active">
                                <a asp-controller="Auth" asp-action="Login">Sign in</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - ConstructionWaste - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ConstructionWaste/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ConstructionWaste</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
              
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Login">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Registration" asp-action="UserRegistration">Registration</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - ConstructionWaste - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>